- become: true
  block:
    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory

    - name: Download the helm signing key for the Helm package repositories
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/keyrings/helm-apt-keyring.asc

    - name: Add the Helm apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/helm-apt-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main
        filename: helm
        state: present

    - name: Install helm
      ansible.builtin.package:
        name: helm
        state: latest

- name: Install helm plugins
  become: true
  become_user: admin
  kubernetes.core.helm_plugin:
    plugin_path: '{{ item }}'
  with_items:
    - https://github.com/databus23/helm-diff

- name: Add helm completion for bash
  become: true
  become_user: admin
  ansible.builtin.lineinfile:
    path: ~/.bash_completion
    create: true
    mode: '0644'
    line: . <(helm completion bash)
