- name: Create admin user
  become: true
  ansible.builtin.user:
    name: admin
    comment: Admin
    create_home: true
    shell: /bin/bash
    password: '*'
    generate_ssh_key: false
    state: present
  register: admin_user

- name: Add admin key to ~/.ssh/authorized_keys
  become: true
  ansible.posix.authorized_key:
    user: '{{ admin_user.name }}'
    key: '{{ admin_key }}'
    manage_dir: true
    state: present
