- become: true
  block:
    - name: Install packages
      ansible.builtin.package:
        name:
          - acl
          - python3-yaml
          - python3-cryptography
          - git

    - name: Create /etc/ansible directory
      ansible.builtin.file:
        path: /etc/ansible
        mode: '2755'
        owner: admin
        state: directory
