- become: true
  block:
    - name: Install packages
      ansible.builtin.package:
        name: acl

    - name: Create /etc/ansible directory
      ansible.builtin.file:
        path: /etc/ansible
        mode: '2755'
        owner: ansible
        state: directory
