admin_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICu3XoHZYEQ2tLebTKwSflvR2ILgcKAgEThHcWWNG/jI
ntp_servers:
    - ntp1.inrim.it
    - ntp2.inrim.it
editor: vim
lang: en_US.UTF-8
language: en_US
domain: home.arpa
timezone: Etc/UTC
zram_size: min(ram / 2, 1024)

ingress_nginx_external_ip: 100.64.0.2
