admin_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICu3XoHZYEQ2tLebTKwSflvR2ILgcKAgEThHcWWNG/jI
ntp_server: time.cloudflare.com
editor: vim
lang: en_US.UTF-8
language: en_US
domain: fritz.box

ingress_nginx_external_ip: 100.64.0.2
