kubernetes_version: 1.28
cri_socket: unix:///run/containerd/containerd.sock
kubernetes_cluster_name: home
kubernetes_control_plane_endpoint: k8s
kubernetes_pod_subnet: 10.44.0.0/16
kubernetes_control_plane_taints: []
kubernetes_request_timeout: 15s
kubernetes_tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
replicas: 1
kubelet_service: /lib/systemd/system/kubelet.service
kubelet_config: /var/lib/kubelet/config.yaml
