- become: true
  become_user: admin
  block:
    - name: Add Cilium helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: Get cilium release
      kubernetes.core.helm_info:
        name: cilium
        release_namespace: kube-system
      register: cilium_release

    - name: Install Cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        wait: true
        update_repo_cache: true
        values: '{{ lookup("template", "values.yaml.j2") | from_yaml }}'
      when: >-
        cilium_release.status is not defined
        or cilium_release.status.status != 'DEPLOYED'
        or (force_cilium | default(false))
