- name: Create ~/.kube directory
  become: true
  become_user: admin
  ansible.builtin.file:
    path: ~/.kube
    state: directory

- name: Read /etc/kubernetes/admin.conf from first control plane node
  become: true
  ansible.builtin.slurp:
    src: /etc/kubernetes/admin.conf
  register: kubeconfig
  delegate_to: '{{ groups["kubernetescontrolplane"][0] }}'

- name: Copy kubeconfig to ~/.kube/config
  become: true
  become_user: admin
  ansible.builtin.copy:
    dest: ~/.kube/config
    content: '{{ kubeconfig.content | b64decode }}'
    force: true
    mode: '0600'
