- name: Install tmux
  become: true
  ansible.builtin.package:
    name: tmux

- block:
    - name: Create ~/.config/tmux directory
      ansible.builtin.file:
        path: ~/.config/tmux
        state: directory

    - name: Copy tmux configuration
      ansible.builtin.copy:
        dest: ~/.config/tmux/tmux.conf
        src: tmux.conf
        mode: '0644'
        force: true
