- name: Install container runtime
  hosts: kubernetesnodes
  roles: [containerd]

- name: Bootstrap cluster
  hosts: kubernetescontrolplane
  roles:
    - kubernetes_control_plane
    - kubeconfig
    - helm
    - cilium_cli
  tasks:
    - name: Install cilium
      become: true
      become_user: admin
      ansible.builtin.import_tasks: tasks/install_helm_release.yaml
      vars:
        release_name: cilium
        release_namespace: kube-system
        repo_url: https://helm.cilium.io/
        create_namespace: false
        values: '{{ lookup("template", "cilium_values.yaml.j2") | from_yaml }}'
