- name: Set up ansible host
  hosts: all
  roles: [ansible]

- name: Set up common things
  hosts: all
  roles:
    - locale
    - etchosts
    - pki
    - ntp
    - vim
    - editor
    - tmux

- name: Configure Raspberry Pis
  hosts: rpis
  roles: [raspberrypi]
